[connections.snowflake]
account = "PEUNPIB-IBB58478"
password = "Brahim@Snowflake2025"
user = "BREGUIGUI"
role = "SYSADMIN"
warehouse = "compute_wh"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true